# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c9b7c838786a7550216b63435121a64faeb11955e9d3feb41ded7bb18e45db25dc156e2757fbc03be8eb49a960280ba9ee175952633fa3bfb40b619a476eb5e

test:
  secret_key_base: a45d16b52caa62c4b564d05e41d3fccff1c8ba50a0b77b0becbcfdf773d00cca98d2fccbaa89b6fa1294d81bc5c1cfa70ef6368e4baec8daf968b619c121c354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
